apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.nsc.com #<plural>.<group>
  namespace: pratap #optional
spec:
  group: nsc.com
  names:
    kind: User
    plural: users
    singular: user
    shortNames:
      - u
      - ur
      - us
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "user object structure"
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  nullable: false
                email:
                  type: string
                  format: email
                  nullable: false
                phone:
                  type: integer
                  format: int64
                  nullable: false
                  minLength: 10
                  maxLength: 10

